# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7tfUecmhHc3EfvCaoq7D6hcYZuDk25B

Before starting the Streamlit app, you need to expose your API key to the environment in your terminal:

```
export HUGGINGFACEHUB_API_TOKEN="your_actual_api_key_here"
```
On Windows Command Prompt, use
```
`set HUGGINGFACEHUB_API_TOKEN="your_api_key"`
```
or in PowerShell use
```
`$env:HUGGINGFACEHUB_API_TOKEN="your_api_key"`)*
```

Then, run the application:

```
streamlit run app.py
```
"""

import os
import sys

# Attempt to import Streamlit first, as we need it to display errors nicely in the web UI
try:
    import streamlit as st
except ModuleNotFoundError:
    print("Streamlit is not installed. Please run: pip install streamlit")
    sys.exit(1)

# Wrap the rest of the LangChain imports in a try-except block to gracefully handle missing dependencies
try:
    from langchain_huggingface import HuggingFaceEmbeddings, HuggingFaceEndpoint, ChatHuggingFace
    from langchain_chroma import Chroma
    from langchain_classic.chains import create_retrieval_chain
    from langchain_classic.chains.combine_documents import create_stuff_documents_chain
    from langchain_core.prompts import ChatPromptTemplate
except ModuleNotFoundError as e:
    st.error(f"⚠️ Import Error: `{e}`")
    st.info(
        "It looks like you are missing some required libraries. "
        "Please stop the Streamlit server (Ctrl+C in your terminal) and run the following command:\n\n"
        "`pip install langchain langchain-community langchain-chroma langchain-huggingface langchain-classic sentence-transformers chromadb transformers`"
    )
    st.stop()

# --- 1. SET UP THE APPLICATION UI ---
st.set_page_config(page_title="PML Knowledge Bot", page_icon="🤖")
st.title("📚 Personalized Machine Learning Assistant")
st.markdown("Ask me anything about recommender systems based on Julian McAuley's textbook.")

# Ensure the HuggingFace API token is set in the environment
if "HUGGINGFACEHUB_API_TOKEN" not in os.environ:
    st.error("⚠️ Hugging Face API token not found!")
    st.info("Please set it in your terminal before running Streamlit:\n\n`export HUGGINGFACEHUB_API_TOKEN='your_hf_token_here'`")
    st.stop()

# --- 2. LOAD THE DATA SOURCE & AI LOGIC ---
# We use st.cache_resource so the database doesn't reload every time the user types
@st.cache_resource
def load_rag_chain():
    # 1. Load the exact same local embeddings used in ingest.py
    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

    # 2. Load the database we created
    vectorstore = Chroma(
        persist_directory="./chroma_db",
        embedding_function=embeddings
    )
    retriever = vectorstore.as_retriever(search_kwargs={"k": 3}) # Get top 3 most relevant chunks

    # 3. Initialize the HuggingFace LLM using the Endpoint
    llm = HuggingFaceEndpoint(
        repo_id="Qwen/Qwen2.5-7B-Instruct",
        max_new_tokens=512,
        temperature=0.1,
        do_sample=False,
    )

    # Wrap the LLM in ChatHuggingFace to properly map the conversational task for the API providers
    chat_model = ChatHuggingFace(llm=llm)

    # 4. Create the strict prompt that bounds the AI to our textbook
    system_prompt = (
        "You are an instructional assistant for a course on Personalized Machine Learning. "
        "Use the following pieces of retrieved context to answer the question. "
        "If you don't know the answer or if the answer is not in the context, "
        "just say that you don't know. Do NOT make up an answer.\n\n"
        "Context: {context}"
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
    ])

    # 5. Chain them together using the chat_model instead of the base llm
    question_answer_chain = create_stuff_documents_chain(chat_model, prompt)
    rag_chain = create_retrieval_chain(retriever, question_answer_chain)

    return rag_chain

# Initialize the RAG chain
chain = load_rag_chain()

# --- 3. BUILD THE CHAT INTERFACE ---
# Initialize chat history in Streamlit session state
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display previous chat messages
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Accept user input
if user_query := st.chat_input("What is matrix factorization?"):
    # Add user message to chat history and display it
    st.session_state.messages.append({"role": "user", "content": user_query})
    with st.chat_message("user"):
        st.markdown(user_query)

    # Generate the bot's response
    with st.chat_message("assistant"):
        with st.spinner("Searching the textbook..."):
            try:
                response = chain.invoke({"input": user_query})
                answer = response["answer"]

                # Streamlit uses $ and $$ for LaTeX, but many LLMs output \( \) and \[ \]
                # This simple replacement ensures the math renders perfectly
                answer = answer.replace('\\[', '$$').replace('\\]', '$$').replace('\\(', '$').replace('\\)', '$')

                st.markdown(answer)
                # Add assistant response to chat history
                st.session_state.messages.append({"role": "assistant", "content": answer})
            except Exception as e:
                st.error(f"An error occurred while generating the response: {e}")