# -*- coding: utf-8 -*-
"""data_ingest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H25goCXm3UwFXLJx4juCCATRQRm_rKV_
"""

pip install langchain_community langchain_text_splitters langchain_openai langchain_community chromadb bs4 langchain_huggingface sentence-transformers

import os
import sys

# Wrap imports in a try-except block to gracefully handle missing dependencies
try:
    # We use LangChain's community document loaders to read the webpage
    from langchain_community.document_loaders import WebBaseLoader
    # Text splitter breaks the large book into smaller chunks
    from langchain_text_splitters import RecursiveCharacterTextSplitter
    # Local embeddings run on your machine - no API key needed!
    from langchain_huggingface import HuggingFaceEmbeddings
    # Chroma is our local vector database
    from langchain_community.vectorstores import Chroma
except ModuleNotFoundError as e:
    print(f"Import Error: {e}")
    print("\nIt looks like you are missing some required libraries.")
    print("Please run the following command in your terminal to install them:")
    print("pip install langchain langchain-community langchain-huggingface sentence-transformers langchain-text-splitters chromadb bs4")
    sys.exit(1)

def create_data_source():
    print("1. Loading textbook from the web...")
    url = "https://cseweb.ucsd.edu/~jmcauley/pml/"
    loader = WebBaseLoader(url)
    docs = loader.load()

    print("2. Splitting text into manageable chunks...")
    # We split the text into chunks of 1000 characters.
    # The 'overlap' ensures that sentences split across chunks don't lose context.
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200
    )
    splits = text_splitter.split_documents(docs)

    print(f"Created {len(splits)} chunks of text.")

    print("3. Generating embeddings and building the vector database...")
    # We use a fast, reliable local model from HuggingFace.
    # It will download automatically the first time you run this script.
    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

    vectorstore = Chroma.from_documents(
        documents=splits,
        embedding=embeddings,
        persist_directory="./chroma_db"
    )

    print("Success! Data source created and saved to './chroma_db'.")

if __name__ == "__main__":
    create_data_source()